test2/test2/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HRAPP.BL.Concrete;
using test2.Models;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json.Serialization;

namespace test2.Controllers
{
    public class CompanyController : Controller
    {
        public ActionResult Company()
        {
            try
            {
                int id = UserBL.ReadAll().First(u => u.Name == User.Identity.GetUserName()).Id;
                var company = (CompanyViewModel)CompanyBL.Read(Convert.ToInt32(id));
                //ERROR Couldn't convert
                //company.Employees = (EmployeeViewModel)EmployeeBL.ReadByCompany(company.Id);
                if(company.Employees == null) company.Employees = new List<EmployeeViewModel>();
                if(company.Groups == null) company.Groups = new List<GroupViewModel>();
                if(company.Positions == null) company.Positions = new List<PositionViewModel>();

                return View(company);
            }
            catch (Exception)
            {
                return View((CompanyViewModel)CompanyBL.Read(Convert.ToInt32(-1)));
                throw;
            }
            
            
        }

        [HttpGet]
        public ActionResult Edit()
        {
            return View();
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public bool Edit(CompanyViewModel viewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    int id = UserBL.ReadAll().First(u => u.Name == User.Identity.GetUserName()).Id;
                    var oldModel = (CompanyViewModel)CompanyBL.Read(Convert.ToInt32(id));
                    oldModel.Name = viewModel.Name;
                    oldModel.Address = viewModel.Address;
                    oldModel.Mail = viewModel.Mail;
                    CompanyBL.Update(oldModel);
                    return true;
                }
                throw new Exception();
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
                throw;
            }
            
        }

        

        
    }
}

test2/test2/Controllers/RecruitmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace test2.Controllers
{
    public class RecruitmentController : Controller
    {
        // GET: Recruitment
        public ActionResult Recruitment()
        {
            return View();
        }

        public ActionResult FindApplication()
        {
            return View();
        }

        public ActionResult FindSend()
        {
            return View();
        }

        public ActionResult FindWait()
        {
            return View();
        }

        public ActionResult Test()
        {
            return View();
        }

    }
}

test2/test2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <meta name="description" content="My ASP.NET Application" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    @Styles.Render("~/bundles/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("HR SAAS APP", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Компания", "Company", "Company")</li>
                    <li>@Html.ActionLink("Рекрутмент", "Recruitment", "Recruitment")</li>
                    
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr/>

        <footer>
            <br/>
            <br/>
            <hr/>
            <p>&copy; @DateTime.Now.Year - HR SAAS APP</p>
        </footer>
    </div>
    

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>